  0%|          | 0/14 [00:00<?, ?it/s][WARNING|logging.py:328] 2025-03-17 20:56:23,244 >> It is strongly recommended to train Gemma2 models with the `eager` attention implementation instead of `flash_attention_2`. Use `eager` with `AutoModelForCausalLM.from_pretrained('<path-to-checkpoint>', attn_implementation='eager')`.
[2025-03-17 20:56:51,709] [WARNING] [stage3.py:2114:step] 1 pytorch allocator cache flushes since last step. this happens when there is high memory pressure and is detrimental to performance. if this is happening frequently consider adjusting settings to reduce memory consumption. If you are unable to make the cache flushes go away consider adding get_accelerator().empty_cache() calls in your training loop to ensure that all ranks flush their caches at the same time
100%|██████████| 14/14 [06:14<00:00, 26.61s/it][INFO|trainer.py:2584] 2025-03-17 21:02:37,469 >>
{'loss': 0.2955, 'grad_norm': 1.1287902349877263, 'learning_rate': 4.937319780454559e-06, 'epoch': 0.13}
{'loss': 0.3068, 'grad_norm': 2.4562984927883216, 'learning_rate': 3.5847093477938955e-06, 'epoch': 0.67}
{'loss': 0.2553, 'grad_norm': 1.0779410861116576, 'learning_rate': 9.412754953531664e-07, 'epoch': 1.33}

Training completed. Do not forget to share your model on huggingface.co/models =)


100%|██████████| 14/14 [06:14<00:00, 26.73s/it]
{'train_runtime': 375.2577, 'train_samples_per_second': 5.095, 'train_steps_per_second': 0.037, 'train_loss': 0.2530574713434492, 'epoch': 1.87}
***** train metrics *****
  epoch                    =     1.8667
  total_flos               =     5400GF
  train_loss               =     0.2531
  train_runtime            = 0:06:15.25
  train_samples            =        956
  train_samples_per_second =      5.095
  train_steps_per_second   =      0.037
2025-03-17 21:02:37 - INFO - __main__ - *** Save model ***
[INFO|trainer.py:3801] 2025-03-17 21:02:42,769 >> Saving model checkpoint to /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2
[INFO|configuration_utils.py:414] 2025-03-17 21:02:42,775 >> Configuration saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/config.json
[INFO|configuration_utils.py:865] 2025-03-17 21:02:42,778 >> Configuration saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/generation_config.json
[INFO|modeling_utils.py:3042] 2025-03-17 21:04:08,286 >> The model is bigger than the maximum size per checkpoint (5GB) and is going to be split in 4 checkpoint shards. You can find where each parameters has been saved in the index located at /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/model.safetensors.index.json.
[INFO|tokenization_utils_base.py:2646] 2025-03-17 21:04:08,291 >> tokenizer config file saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/tokenizer_config.json
[INFO|tokenization_utils_base.py:2655] 2025-03-17 21:04:08,293 >> Special tokens file saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/special_tokens_map.json
[INFO|trainer.py:3801] 2025-03-17 21:04:14,284 >> Saving model checkpoint to /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2
[INFO|configuration_utils.py:414] 2025-03-17 21:04:14,290 >> Configuration saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/config.json
[INFO|configuration_utils.py:865] 2025-03-17 21:04:14,293 >> Configuration saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/generation_config.json
[INFO|modeling_utils.py:3042] 2025-03-17 21:05:40,605 >> The model is bigger than the maximum size per checkpoint (5GB) and is going to be split in 4 checkpoint shards. You can find where each parameters has been saved in the index located at /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/model.safetensors.index.json.
[INFO|tokenization_utils_base.py:2646] 2025-03-17 21:05:40,610 >> tokenizer config file saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/tokenizer_config.json
[INFO|tokenization_utils_base.py:2655] 2025-03-17 21:05:40,612 >> Special tokens file saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/special_tokens_map.json
events.out.tfevents.1742259382.h1compute00.ihc.umd.edu.2643144.0: 100%|██████████| 7.26k/7.26k [00:00<00:00, 49.9kB/s]
tokenizer.json: 100%|██████████| 34.4M/34.4M [00:00<00:00, 51.0MB/s]0<02:02, 39.9MB/s]
tokenizer.model: 100%|██████████| 4.24M/4.24M [00:00<00:00, 31.6MB/s]<03:09, 25.7MB/s]
training_args.bin: 100%|██████████| 7.35k/7.35k [00:00<00:00, 123kB/s]01:31, 53.7MB/s]
model-00004-of-00004.safetensors: 100%|██████████| 3.67G/3.67G [01:27<00:00, 41.7MB/s]
model-00003-of-00004.safetensors: 100%|██████████| 4.96G/4.96G [01:48<00:00, 45.7MB/s]0/7.26k [00:00<?, ?B/s]
model-00001-of-00004.safetensors: 100%|██████████| 4.90G/4.90G [01:49<00:00, 44.8MB/s]
model-00002-of-00004.safetensors: 100%|██████████| 4.95G/4.95G [01:57<00:00, 42.1MB/s]
Upload 8 LFS files: 100%|██████████| 8/8 [01:57<00:00, 14.70s/it]1:49<00:14, 29.3MB/s]
[INFO|configuration_utils.py:414] 2025-03-17 21:08:25,981 >> Configuration saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/config.json
[INFO|trainer.py:3801] 2025-03-17 21:08:30,217 >> Saving model checkpoint to /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2
[INFO|configuration_utils.py:414] 2025-03-17 21:08:30,222 >> Configuration saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/config.json
2025-03-17 21:08:25 - INFO - __main__ - Model saved to /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2
2025-03-17 21:08:25 - INFO - __main__ - Pushing to hub...
[INFO|configuration_utils.py:865] 2025-03-17 21:08:30,225 >> Configuration saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/generation_config.json
[INFO|modeling_utils.py:3042] 2025-03-17 21:09:59,634 >> The model is bigger than the maximum size per checkpoint (5GB) and is going to be split in 4 checkpoint shards. You can find where each parameters has been saved in the index located at /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/model.safetensors.index.json.
[INFO|tokenization_utils_base.py:2646] 2025-03-17 21:09:59,640 >> tokenizer config file saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/tokenizer_config.json
[INFO|tokenization_utils_base.py:2655] 2025-03-17 21:09:59,642 >> Special tokens file saved in /beacon-scratch/tongzh24//gemma-2-9b-it/mixed_unique_conclusion/OP_final_10_2_3Rounds/ft_iter_2/special_tokens_map.json
Traceback (most recent call last):
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models/TongZheng1999/gemma-2-9b-it-star-mixed_unique_conclusion-OP-final_10-2-3Rounds-iter-2/commit/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ihchomes/tongzh24/logical_reasoning/Truth_Table_Logical_Reasoning/alignment-handbook/scripts/run_sft.py", line 225, in <module>
    main()
  File "/ihchomes/tongzh24/logical_reasoning/Truth_Table_Logical_Reasoning/alignment-handbook/scripts/run_sft.py", line 219, in main
    trainer.push_to_hub(**kwargs)
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/transformers/trainer.py", line 4651, in push_to_hub
    return upload_folder(
           ^^^^^^^^^^^^^^
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1551, in _inner
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 4707, in upload_folder
    commit_info = self.create_commit(
                  ^^^^^^^^^^^^^^^^^^^
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1551, in _inner
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 4083, in create_commit
    hf_raise_for_status(commit_resp, endpoint_name="commit")
  File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 481, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models/TongZheng1999/gemma-2-9b-it-star-mixed_unique_conclusion-OP-final_10-2-3Rounds-iter-2/commit/main (Request ID: Root=1-67d8c815-6d6145fc5c6bbd8050f7514c;2e839912-6b25-42a1-8832-a54fd6151c28)

Internal Error - We're working hard to fix this as soon as possible!
[rank0]: Traceback (most recent call last):
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
[rank0]:     response.raise_for_status()
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
[rank0]:     raise HTTPError(http_error_msg, response=self)
[rank0]: requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models/TongZheng1999/gemma-2-9b-it-star-mixed_unique_conclusion-OP-final_10-2-3Rounds-iter-2/commit/main

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/ihchomes/tongzh24/logical_reasoning/Truth_Table_Logical_Reasoning/alignment-handbook/scripts/run_sft.py", line 225, in <module>
[rank0]:     main()
[rank0]:   File "/ihchomes/tongzh24/logical_reasoning/Truth_Table_Logical_Reasoning/alignment-handbook/scripts/run_sft.py", line 219, in main
[rank0]:     trainer.push_to_hub(**kwargs)
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/transformers/trainer.py", line 4651, in push_to_hub
[rank0]:     return upload_folder(
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1551, in _inner
[rank0]:     return fn(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 4707, in upload_folder
[rank0]:     commit_info = self.create_commit(
[rank0]:                   ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1551, in _inner
[rank0]:     return fn(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 4083, in create_commit
[rank0]:     hf_raise_for_status(commit_resp, endpoint_name="commit")
[rank0]:   File "/beacon-scratch/tongzh24/miniconda3/envs/logical_reasoning/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 481, in hf_raise_for_status
[rank0]:     raise _format(HfHubHTTPError, str(e), response) from e
[rank0]: huggingface_hub.errors.HfHubHTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models/TongZheng1999/gemma-2-9b-it-star-mixed_unique_conclusion-OP-final_10-2-3Rounds-iter-2/commit/main (Request ID: Root=1-67d8c815-6d6145fc5c6bbd8050f7514c;2e839912-6b25-42a1-8832-a54fd6151c28)

[rank0]: Internal Error - We're working hard to fix this as soon as possible!
